### ISSUE TITLE
Не кроссплатформенный тест

### ISSUE THREAD

**Issue by Quirel** [Quirel/sportnet#8]
https://github.com/Quirel/sportnet/blob/a94875ec3531dc6eb694c40eab73448bf3d8a1b7/sportnet/sportnet/authapp/tests/test_models.py#L56

Заменить `Path.join`

**Comment by Quirel** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Исправтиь тест модели User](https://trello.com/c/QRWvl3W2/38-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D1%82%D0%B8%D1%8C-%D1%82%D0%B5%D1%81%D1%82-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D0%B8-user)

**Comment by Quirel** [comment]
fix
https://github.com/Quirel/sportnet/pull/9

**Comment by AVMitrohin** [comment]
Исправлено

**Comment by AVMitrohin** [comment]
Ок
